export const actionsTypes = {
  GET_VIDEO: "GET_VIDEO",
  DELETE_SINGLE_VIDEO: "DELETE_SINGLE_VIDEO",
  DELETE_SINGLE_LIKES_VIDEO: "DELETE_SINGLE_LIKES_VIDEO",
  DELETE_ALL_VIDEOS: "DELETE_ALL_VIDEOS",
  ADD_TO_LIKES: "ADD_TO_LIKES",
  SHOW_LIKES_VIDEOS: "SHOW_LIKES_VIDEOS",
  SHOW_ALL_VIDEOS: "SHOW_ALL_VIDEOS",
  SELECT_VIDEOS_LIST_VIEW: "SELECT_VIDEOS_LIST_VIEW",
  IS_HOVER_TRUE: "IS_HOVER_TRUE",
  IS_HOVER_FALSE: "IS_HOVER_FALSE",
};
